quarkus.camel.openapi.expose.enabled=true

%test.quarkus.otel.sdk.disabled=true

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h "%r" %s %b %D ms

# OpenAPI info
quarkus.smallrye-openapi.info-title=Meteo Public API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Running conditions rating based on air quality and weather forecast
