quarkus.swagger-ui.always-include = true
quarkus.smallrye-openapi.servers = http://meteo-public-apps-dev.apps.piomin.centralus.aroapp.io

quarkus.otel.exporter.otlp.endpoint = http://cluster-collector-collector.otel.svc.cluster.local:4317
quarkus.otel.enabled = true
quarkus.otel.traces.enabled = true
quarkus.otel.propagators = tracecontext,baggage
camel.opentelemetry2.enabled = true

quarkus.openshift.route.expose = true