quarkus.oidc.auth-server-url = ${KEYCLOAK_BASE_URL}/realms/master
quarkus.oidc.client-id = quarkus-app
quarkus.oidc.credentials.secret = ${KEYCLOAK_CLIENT_SECRET}

quarkus.swagger-ui.always-include = true
quarkus.smallrye-openapi.servers = http://person-rest-api-apps.apps.piomin-aws-main.5fuc.p1.openshiftapps.com/