quarkus.oidc.auth-server-url = ${KEYCLOAK_BASE_URL}/realms/master
quarkus.oidc.client-id = quarkus-app
quarkus.oidc.credentials.secret = ${KEYCLOAK_CLIENT_SECRET}

quarkus.swagger-ui.always-include = true
quarkus.smallrye-openapi.servers = ${APP_URL}

quarkus.otel.exporter.otlp.endpoint = http://cluster-collector-collector.otel.svc.cluster.local:4317
quarkus.otel.enabled = true
quarkus.otel.traces.enabled = true
#quarkus.otel.service.name=kafka-nbp
quarkus.otel.propagators = tracecontext,baggage
camel.opentelemetry2.enabled = true